baseURL = 'https://santosrac.netlify.app/'
languageCode = 'en-us'
DefaultContentLanguage = 'en'
title = 'Dr. Renato A. Corrêa dos Santos'
theme = "colordrop"

[params]
themeColor = "#000000"
themeInverseColor = "#ffffff"
description = "Hi, I'm Renato Santos, a Ph.D in Genetics and Molecular Biology from Brazil; I graduated in November of 2021 and currently develop my post-doctoral research in the Computational, Evolutionary, and Systems Biology Laboratory (LabBCES)! I'm interested in Bioinformatics and I love teaching programming skills to bioscientists. I'm also concerned about several aspects of how research is conducted today, and have actively engaged in formal and informal projects involving reproducibility and mental health in science!"
siteLogo = "img/me.JPG"
images = "img/me.JPG"

[menu]
[[menu.main]]
    name = "Curriculum"
    url = "/curriculum/"
    weight = 3
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
[[menu.main]]
    name = "Active initiatives"
    url = "/active_initiaves/"
    weight = 2
[[menu.main]]
    name = "Collaborations"
    url = "/collaborations/"
    weight = 6
[[menu.footer]]
	name = "github"
	url = "https://github.com/SantosRAC"
    weight = 1
[[menu.footer]]
	name = "twitter"
	url = "https://twitter.com/CorreaSantosRA"
    weight = 2
[[menu.footer]]
      name = "curriculum"
      url = "/curriculum/"
    weight = 3