baseURL = 'https://santosrac.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "colordrop"

[params]
themeColor = "#000000"
themeInverseColor = "#ffffff"

[params]
description = "Welcome to my blog..."
siteLogo = "logo-photo.png"
