baseURL = 'https://santosrac.netlify.app/'
languageCode = 'en-us'
DefaultContentLanguage = 'en'
title = 'Dr. Renato A. Corrêa dos Santos'
theme = "colordrop"

[params]
themeColor = "#000000"
themeInverseColor = "#ffffff"
description = "Hi, I'm Renato Santos, a Ph.D in Genetics and Molecular Biology from Brazil; I graduated in November of last year (2021) and currently a post-doctoral researcher! I'm interested in Bioinformatics and I love to teach programming skills to bioscientists. I'm also concerned about several aspects of how research is conducted today. This year I am an Ambassador for eLife Community (2022-2023 programmee) - I'm so excited about this!"
siteLogo = "img/me.JPG"
images = "img/me.JPG"

[menu]
[[menu.main]]
    name = "curriculum"
    url = "/curriculum/"
    weight = 3
[[menu.main]]
    name = "contact"
    url = "/contact/"
    weight = 5
[[menu.main]]
    name = "active initiatives"
    url = "/active_initiaves/"
    weight = 2
[[menu.main]]
    name = "collaborations"
    url = "/collaborations/"
    weight = 4
[[menu.footer]]
	name = "github"
	url = "https://github.com/SantosRAC"
    weight = 1
[[menu.footer]]
	name = "twitter"
	url = "https://twitter.com/CorreaSantosRA"
    weight = 2
[[menu.footer]]
      name = "curriculum"
      url = "/curriculum/"
    weight = 3
