baseURL = 'https://santosrac.netlify.app/'
languageCode = 'en-us'
title = 'Dr. Renato A. Corrêa dos Santos'
theme = "colordrop"

[params]
themeColor = "#000000"
themeInverseColor = "#ffffff"
description = "Hi, I'm Renato Santos, a Ph.D in Genetics and Molecular Biology from Brazil; I graduated in November this year (2021) and will hopefully become a post-doctoral researcher soon! I'm interested in bioinformatics and I love to teach programming skills to bioscientists. I'm also concerned about several aspects of how research is conducted today. Next year I'll be an Ambassador for eLife Community - I'm so excited about this!"
siteLogo = "img/me.JPG"
images = "img/me.JPG"

[[menu.main]]
    name = "curriculum"
    url = "/curriculum/"
    weight = 3
[[menu.main]]
    name = "contact"
    url = "/contact/"
    weight = 5
[[menu.main]]
    name = "active initiatives"
    url = "/active_initiaves/"
    weight = 2
[[menu.main]]
    name = "collaborations"
    url = "/collaborations/"
    weight = 4

[[menu.footer]]
	name = "github"
	url = "https://github.com/SantosRAC"
    weight = 1
[[menu.footer]]
	name = "twitter"
	url = "https://twitter.com/CorreaSantosRA"
    weight = 2
[[menu.footer]]
      name = "curriculum"
      url = "/curriculum/"
    weight = 3

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
  [languages.br-pt]
    languageName = 'Português Brasileiro'
    description = "Olá! Sou Renato Santos."
    weight = 2