baseURL = 'https://santosrac.netlify.app/'
languageCode = 'en-us'
title = 'Dr. Renato Augusto Corrêa dos Santos'
theme = "colordrop"

[params]
themeColor = "#000000"
themeInverseColor = "#ffffff"
description = "Welcome to my blog..."
siteLogo = "logo-photo.png"
