baseURL = 'https://santosrac.netlify.app/'
languageCode = 'en-us'
title = 'Dr. Renato A. Corrêa dos Santos'
theme = "colordrop"

[params]
themeColor = "#000000"
themeInverseColor = "#ffffff"
description = ""
siteLogo = "img/me.JPG"
images = "img/me.JPG"

[[menu.main]]
    name = "about"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "curriculum"
    url = "/curriculum/"
    weight = 2
[[menu.main]]
    name = "contact"
    url = "/contact/"
    weight = 3
[[menu.main]]
    name = "active initiatives"
    url = "/active_initiaves/"
    weight = 4
[[menu.main]]
    name = "collaborations"
    url = "/collaborations/"
    weight = 5

[[menu.footer]]
	name = "github"
	url = "https://github.com/SantosRAC"
    weight = 1
[[menu.footer]]
	name = "twitter"
	url = "https://twitter.com/CorreaSantosRA"
    weight = 2
[[menu.footer]]
      name = "curriculum"
      url = "/curriculum/"
    weight = 3
