baseURL = 'https://santosrac.netlify.app/'
languageCode = 'en-us'
title = 'Dr. Renato Augusto Corrêa dos Santos'
theme = "colordrop"

[params]
themeColor = "#000000"
themeInverseColor = "#ffffff"
description = "My academic life"
siteLogo = "img/me.JPG"
images:
- img/me.JPG