baseURL = 'https://santosrac.netlify.app/'
languageCode = 'en-us'
title = 'Dr. Renato Augusto Corrêa dos Santos'
theme = "colordrop"

[params]
themeColor = "#000000"
themeInverseColor = "#ffffff"
description = "My academic life"
siteLogo = "img/me.JPG"
images = "img/me.JPG"

[[menu.main]]
    name = "About"
    url = "/About/"
    weight = 1
[[menu.main]]
    name = "curriculum"
    url = "/curriculum/index.md"
    weight = 2
[[menu.main]]
    name = "Collaborations"
    url = "/Collaborations/index.md"
    weight = 3

[[menu.footer]]
	name = "github"
	url = "https://github.com/SantosRAC"
    weight = 1
[[menu.footer]]
	name = "twitter"
	url = "https://twitter.com/CorreaSantosRA"
    weight = 2
[[menu.footer]]
      name = "curriculum"
      url = "curriculum/index.md"
    weight = 3
